- assets/js/app.js
- assets/js/videos/videos.controller.js
- assets/js/videos/videos.factory.js
- assets/js/videos/videos.service.js
- lib/ex_subtil_backend_web/controllers/videos_controller.ex
- lib/ex_subtil_backend_web/router.ex
- lib/ex_subtil_backend_web/templates/page/index.html.eex
- lib/ex_subtil_backend_web/views/videos_view.ex
- mix.exs
> [WIP] Display available videos from VideoFactory

- assets/js/videos/videos.controller.js
- assets/js/videos/videos.service.js
- lib/ex_subtil_backend_web/controllers/videos_controller.ex
- lib/ex_subtil_backend_web/templates/page/index.html.eex
- lib/ex_subtil_backend_web/views/videos_view.ex
Depends on https://github.com/FTV-Subtil/ex_video_factory/pull/10
> Improve video pages management

- assets/src/app/services/video.service.ts
> Sort videos by reversed broadcasting dates

- lib/ex_subtil_backend/workflow/step/ftp_download.ex
- lib/ex_subtil_backend/workflow/step/ftp_upload.ex
- lib/ex_subtil_backend/workflow/step/generate_dash.ex
- lib/ex_subtil_backend/workflow/step/http_download.ex
- lib/ex_subtil_backend/workflow/step/requirements.ex
- lib/ex_subtil_backend/workflow/step/set_language.ex
- lib/ex_subtil_backend/workflow/step/ttml_to_mp4.ex
- test/ex_meetup_amqp/workflow/step/requirements_test.exs
> Add worker path requirements

- assets/src/app/videos/videos.component.html
- assets/src/app/videos/videos.component.less
> Add videos column names

- assets/src/app/app.component.html
- assets/src/app/services/video.service.ts
- assets/src/app/videos/videos.component.html
- assets/src/app/videos/videos.component.ts
> Videos page size

- lib/ex_subtil_backend/workflow/step/http_download.ex
- lib/ex_subtil_backend/workflow/workflows.ex
Set destination directory path as required
> Fix HTTP download path requirement

- assets/src/app/models/video.ts
- assets/src/app/videos/videos.component.html
- assets/src/app/videos/videos.component.less
- lib/ex_subtil_backend_web/views/videos_view.ex
> Add parent link

- assets/src/app/app.module.ts
- assets/src/app/models/video.ts
- assets/src/app/videos/videos.component.html
- assets/src/app/videos/videos.component.less
- assets/src/app/videos/videos.component.ts
> Start multiple jobs

- assets/src/app/models/video.ts
- assets/src/app/videos/videos.component.html
- assets/src/app/videos/videos.component.less
- lib/ex_subtil_backend_web/views/videos_view.ex
> Handle broadcasted_live metadata, and display an icon if true

- assets/src/app/videos/videos.component.html
- assets/src/app/videos/videos.component.less
- lib/ex_subtil_backend/videos/videos.ex
- lib/ex_subtil_backend/workflow/workflow_step.ex
> Display workflow duration

- assets/src/app/pipes/icon_for_job.pipe.ts
- assets/src/app/pipes/job_type.pipe.ts
- assets/src/app/videos/workflow/workflow_dialog.component.ts
- lib/ex_subtil_backend/amqp/job_ffmpeg_completed_consumer.ex
- lib/ex_subtil_backend/amqp/job_ffmpeg_emitter.ex
- lib/ex_subtil_backend/amqp/job_ffmpeg_error_consumer.ex
- lib/ex_subtil_backend/application.ex
- lib/ex_subtil_backend/workflow/step/audio_extraction.ex
- lib/ex_subtil_backend/workflow/step/generate_dash.ex
- lib/ex_subtil_backend/workflow/step/set_language.ex
- lib/ex_subtil_backend/workflow/workflow_step.ex
- test/ex_subtil_backend/workflows/step/generate_dash_test.exs
And set language suffix to audio file name
> Extract audio from HLS MP4

- assets/src/app/pipes/docker_image.pipe.ts
- assets/src/app/pipes/icon_for_job.pipe.ts
- assets/src/app/pipes/job_type.pipe.ts
- assets/src/app/pipes/queue.pipe.ts
- assets/src/app/videos/videos.component.ts
- assets/src/app/videos/workflow/workflow_dialog.component.ts
- lib/ex_subtil_backend/amqp/job_ffmpeg_completed_consumer.ex
- lib/ex_subtil_backend/amqp/job_ffmpeg_emitter.ex
- lib/ex_subtil_backend/amqp/job_ffmpeg_error_consumer.ex
- lib/ex_subtil_backend/application.ex
- lib/ex_subtil_backend/workflow/step/acs/prepare_audio.ex
- lib/ex_subtil_backend/workflow/step/acs/synchronize.ex
- lib/ex_subtil_backend/workflow/step/audio_decode.ex
- lib/ex_subtil_backend/workflow/step/audio_encode.ex
- lib/ex_subtil_backend/workflow/step/audio_extraction.ex
- lib/ex_subtil_backend/workflow/step/generate_dash.ex
- lib/ex_subtil_backend/workflow/step/set_language.ex
- lib/ex_subtil_backend/workflow/step/ttml_to_mp4.ex
- lib/ex_subtil_backend/workflow/workflow_step.ex
- test/ex_subtil_backend/workflows/step/generate_dash_test.exs
> Initialize ACS workflow

- assets/src/app/pipes/docker_image.pipe.ts
- assets/src/app/pipes/queue.pipe.ts
- assets/src/app/videos/workflow/workflow_dialog.component.ts
- config/dev.exs
- config/prod.exs
- lib/ex_subtil_backend/amqp/job_command_line_completed_consumer.ex
- lib/ex_subtil_backend/amqp/job_command_line_emitter.ex
- lib/ex_subtil_backend/amqp/job_command_line_error_consumer.ex
- lib/ex_subtil_backend/application.ex
- lib/ex_subtil_backend/workflow/step/acs/prepare_audio.ex
- lib/ex_subtil_backend/workflow/step/acs/synchronize.ex
- lib/ex_subtil_backend/workflow/step/audio_decode.ex
- lib/ex_subtil_backend/workflow/step/audio_encode.ex
- lib/ex_subtil_backend/workflow/step/audio_extraction.ex
- lib/ex_subtil_backend/workflow/step/clean_workspace.ex
- lib/ex_subtil_backend/workflow/step/ftp_download.ex
- lib/ex_subtil_backend/workflow/step/ftp_upload.ex
- lib/ex_subtil_backend/workflow/step/generate_dash.ex
- lib/ex_subtil_backend/workflow/step/http_download.ex
- lib/ex_subtil_backend/workflow/step/set_language.ex
- lib/ex_subtil_backend/workflow/step/ttml_to_mp4.ex
- lib/ex_subtil_backend_web/controllers/docker/images_controller.ex
> Workflow steps refactoring

- assets/src/app/pipes/queue.pipe.ts
- assets/src/app/videos/workflow/workflow_dialog.component.ts
- lib/ex_subtil_backend/amqp/job_command_line_completed_consumer.ex
- lib/ex_subtil_backend/amqp/job_command_line_emitter.ex
- lib/ex_subtil_backend/amqp/job_command_line_error_consumer.ex
- lib/ex_subtil_backend/application.ex
- lib/ex_subtil_backend/workflow/step/acs/synchronize.ex
- lib/ex_subtil_backend/workflow/step/clean_workspace.ex
For the moment, the ACS step executes a simple copy of the TTML file.
> Add ACS workflow

- assets/src/app/videos/workflow/workflow_dialog.component.ts
> Fix step selection/unselection in videos workflow dialog

- lib/ex_backend_web/controllers/workflow_controller.ex
Is this useful, or should we remove the whole workflow from the UI?
> Fix FTV Subtil ACS workflow parameters

- assets/src/app/login/login.component.html
- assets/src/app/order/order.component.html
- assets/src/app/order/order.component.ts
- assets/src/app/order/orders.component.html
- assets/src/app/order/orders.component.ts
- lib/ex_backend/workflow/definition/francetv_dialog_enhancement.ex
- lib/ex_backend_web/controllers/workflow_controller.ex
Depends on https://github.com/media-io/ex_step_flow/pull/3
> Add FTV dialog enhancement workflow

- assets/src/app/order/order.component.html
- assets/src/app/order/orders.component.html
- assets/src/app/order/orders.component.less
- assets/src/app/order/orders.component.ts
Modified the command GUI :
- to show ACS/ASP/ACS+ASP commands
- to allow user to see/download the results of their workflows
- to allow user to access directly to the workflow GUI
- also to beautify the GUI ❤️
> Modified the command GUI

- lib/ex_backend_web/controllers/s3_controller.ex
- lib/ex_backend_web/views/auth_view.ex
> change to S3 prefix (instead of AWS) and manage errors on presign call

- lib/ex_backend/workflow/definition/ftv_studio_rosetta.ex
Hot fix because ffmepg job expect to retrieve video filename before audio filename but it's not always right.
> Fix issue when retrieving audio & video files into ffmpeg job.

- CHANGELOG.md
Modified changelog tag strategy to avoid modifying changelog after merge to tag new version
> Modified changelog tag strategy

- assets/package.json
- assets/yarn.lock
To support the port parameter in the host URL
> Fix local S3 upload updating evaporate package version

- assets/src/app/app.component.ts
- assets/src/app/authentication/auth-guard.service.ts
- assets/src/app/jobs/jobs.component.ts
- config/config.exs
> Update rights on orders and workflows views
